# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

stages:
- stage: B
  jobs:
  - job: A1
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          echo Hello world
          
          sleep 10
  - job: A2
    dependsOn: A1
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Hello world
            
            sleep 10
  - job: B1
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Hello world
            
            sleep 10
  - job: C1
    dependsOn: [B1,A2]
    
- stage: A
  jobs:
  - job: A1
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
  - job: A2
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: '1111'
        instructions: '2222'
    


      

trigger:
- master

pool:
  vmImage: ubuntu-latest

