# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  jobs:
    - job: A1
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
    - job: A2
      steps:    
        - task: CmdLine@2
          inputs:
            script: |
              echo Write your commands here
              
              echo Hello world
              
              sleep 10


- stage: DeployUS1
  dependsOn: Test    # this stage runs after Test
  jobs:
    - job: B1
- stage: DeployUS3
  dependsOn: DeployUS1    # this stage runs after Test
  jobs:
    - job: B3

- stage: DeployUS2
  dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test
  jobs:
    - job: B2

- stage: DeployEurope
  dependsOn:         # this stage runs after DeployUS1 and DeployUS2
  - DeployUS3
  - DeployUS2
  jobs:
    - job: C1
