# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

stages:
- stage: A
  jobs:
  - job: A1
    dependsOn: A2
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
  - job: A2
    

- stage: B
  jobs:
  - job: B1
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 2
        inputs:
          notifyUsers: '1111'
          instructions: '2222'
  - job: B2

trigger:
- master

pool:
  vmImage: ubuntu-latest

